const db = require('./db');

const PUBLIC_OWNERS = [
  {
    phone: "N/A",
    name: "Public Parking Authority",
    email: "public-authority@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918067266111",
    name: "Phoenix Mall Parking Management",
    email: "phoenix-parking@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918022969300",
    name: "BMRCL Metro Customer Helpline",
    email: "bmrcl-metro@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918030160000",
    name: "Mantri Square Parking Desk",
    email: "mantri-mall@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918066785555",
    name: "BIAL Airport Authority",
    email: "bial-airport@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918067282222",
    name: "Orion Parking Management",
    email: "orion-mall@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918068940000",
    name: "Forum Falcon City Info Desk",
    email: "forum-falcon@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+442087459000",
    name: "Heathrow Parking Services",
    email: "heathrow-t5@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+442033712300",
    name: "Westfield London Guest Services",
    email: "westfield-london@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+17182444444",
    name: "JFK Terminal 4 Parking Desk",
    email: "jfk-t4@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+12122475050",
    name: "Times Square Parking Desk",
    email: "timessquare-garage@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+61292507111",
    name: "Sydney Opera House Car Park Management",
    email: "sydney-opera-house@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+97143627500",
    name: "Dubai Mall Parking Operations",
    email: "dubai-mall@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+81334631211",
    name: "Shibuya District Parking Management",
    email: "shibuya-crossing@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912266851010",
    name: "CSMIA Airport Authority",
    email: "mumbai-airport-t2@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912243339999",
    name: "Phoenix Palladium Parking Desk",
    email: "phoenix-palladium@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+911123363600",
    name: "NDMC CP Parking Management",
    email: "cp-block-e@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+911244797300",
    name: "DIAL Delhi Airport Authority",
    email: "delhi-airport-t3@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+33155825050",
    name: "Paris Gare du Nord Parking Desk",
    email: "paris-garedunord@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+6565956868",
    name: "CAG Changi Airport Parking",
    email: "singapore-changi@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+6566888888",
    name: "MBS Parking Operations",
    email: "singapore-mbs@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+14167763000",
    name: "Pearson Airport Parking Authority",
    email: "toronto-pearson@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+13126160800",
    name: "Millennium Park Parking Garage",
    email: "chicago-millennium@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+14153970300",
    name: "Union Square Garage Office",
    email: "sf-unionsquare@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+27214087500",
    name: "V&A Waterfront Parking Office",
    email: "capetown-waterfront@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+913325111926",
    name: "AAI Kolkata Airport Office",
    email: "kolkata-airport@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914422560551",
    name: "Chennai Airport Parking Helpline",
    email: "chennai-airport@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914066523900",
    name: "RGIA Hyderabad Airport Desk",
    email: "hyderabad-airport@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918022067803",
    name: "Forum Mall Koramangala Parking Info",
    email: "bengaluru-forum@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912222621450",
    name: "CSMT Railway Parking Desk",
    email: "mumbai-csmt@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912223070197",
    name: "Mumbai Central Station Desk",
    email: "mumbai-central@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+911123340000",
    name: "NDLS Station Parking Management",
    email: "delhi-ndls@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+911124359573",
    name: "Hazrat Nizamuddin Parking Desk",
    email: "delhi-nizamuddin@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914425350303",
    name: "Chennai Central Station Desk",
    email: "chennai-central@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+913326601748",
    name: "Howrah Railway Station Desk",
    email: "kolkata-howrah@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914027782613",
    name: "Secunderabad Railway Desk",
    email: "hyderabad-secunderabad@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912026122650",
    name: "Pune Junction Railway Desk",
    email: "pune-junction@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+917922112108",
    name: "Ahmedabad Junction Desk",
    email: "ahmedabad-kalupur@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+911412204550",
    name: "Jaipur Junction Desk",
    email: "jaipur-junction@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914842375131",
    name: "Ernakulam Junction Desk",
    email: "kochi-ernakulam@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914842721111",
    name: "Lulu Mall Kochi Desk",
    email: "lulu-kochi@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912066890000",
    name: "Phoenix Marketcity Pune Desk",
    email: "phoenix-pune@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912261801011",
    name: "Infiniti Mall Andheri Desk",
    email: "infiniti-andheri@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912266490400",
    name: "Inorbit Mall Malad Desk",
    email: "inorbit-malad@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+912261801100",
    name: "Phoenix Marketcity Kurla Desk",
    email: "phoenix-kurla@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+911142666666",
    name: "Select Citywalk Saket Desk",
    email: "select-citywalk@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+911146066600",
    name: "DLF Promenade Vasant Kunj Desk",
    email: "dlf-promenade@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914430083008",
    name: "Phoenix Marketcity Velachery Desk",
    email: "phoenix-velachery@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+913323588100",
    name: "Mani Square Mall Desk",
    email: "manisquare-kolkata@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+913330689999",
    name: "Quest Mall Kolkata Desk",
    email: "questmall-kolkata@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914044888888",
    name: "Inorbit Mall Hyderabad Desk",
    email: "inorbit-hyderabad@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+918022975615",
    name: "Majestic Bus Stand Desk",
    email: "majestic-bus-stand@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914424791300",
    name: "Koyambedu CMBT Desk",
    email: "chennai-cmbt@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+914024618063",
    name: "MGBS Hyderabad Desk",
    email: "hyderabad-mgbs@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+33170363950",
    name: "CDG Airport Parking Authority",
    email: "paris-cdg@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+13106465252",
    name: "LAX Airport Parking Desk",
    email: "lax-parking@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  },
  {
    phone: "+31206019111",
    name: "Schiphol Parking Control",
    email: "schiphol-parking@n-a.com",
    password_hash: "N/A",
    joined_at: Date.now() / 1000
  }
];

const PUBLIC_LISTINGS = [
  {
    id: "pub_phoenix_whitefield",
    title: "Phoenix Marketcity Parking (Whitefield)",
    desc: "Multilevel secure parking facility at Phoenix Marketcity Mall. 24/7 security patrol and camera coverage.",
    area_landmark: "Phoenix Marketcity Mall, Whitefield",
    price_hourly: 30,
    price_daily: 200,
    price_monthly: 3000,
    lat: 12.9977,
    lng: 77.6966,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Phoenix+Marketcity/@12.9977,77.6966,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918067266111",
    is_sold: false,
    address_text: "Whitefield Main Road, Devasandra Industrial Estate, Krishnarajapura, Bengaluru, Karnataka 560048"
  },
  {
    id: "pub_ksr_majestic",
    title: "KSR Bengaluru Railway Station General Parking",
    desc: "Spacious open and covered parking options near the main entry gates of KSR Bengaluru Station. Convenient for passengers and short layovers.",
    area_landmark: "Majestic Railway Station Main Entrance",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1, // N/A
    lat: 12.9784,
    lng: 77.5696,
    length: 16,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/KSR+Bengaluru+City+Railway+Station/@12.9784,77.5696,17z",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "N/A",
    is_sold: false,
    address_text: "Kempegowda, Majestic, Bengaluru, Karnataka 560023"
  },
  {
    id: "pub_indiranagar_metro",
    title: "BMRCL Parking - Indiranagar Metro Station",
    desc: "Official transit parking lot managed by BMRCL. Perfect for daily commuters riding the Purple Line. Covered space with lockable gates.",
    area_landmark: "Indiranagar Metro Station, 100 Ft Rd",
    price_hourly: -1, // N/A
    price_daily: -1,  // N/A
    price_monthly: -1, // N/A
    lat: 12.9783,
    lng: 77.6385,
    length: 14,
    breadth: 7,
    amenities: ['CCTV Camera', 'Gate Lock'],
    gmap_link: "https://www.google.com/maps/place/Indiranagar+Metro+Station/@12.9783,77.6385,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918022969300",
    is_sold: false,
    address_text: "Stage 2, Indiranagar, Bengaluru, Karnataka 560038"
  },
  {
    id: "pub_mantri_mall",
    title: "Mantri Square Mall Parking Lot",
    desc: "Underground parking spaces with digital guidance systems. Direct access bridge to Mantri Square Sampige Road metro station.",
    area_landmark: "Mantri Square Mall, Sampige Road",
    price_hourly: 40,
    price_daily: 250,
    price_monthly: -1, // N/A
    lat: 12.9918,
    lng: 77.5712,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Mantri+Square+Mall/@12.9918,77.5712,17z",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918030160000",
    is_sold: false,
    address_text: "Sampige Rd, Malleshwaram, Bengaluru, Karnataka 560003"
  },
  {
    id: "pub_airport_t1",
    title: "KIA T1 General & Long-Term Parking",
    desc: "Spacious long-term parking at Kempegowda International Airport. Safe and secure slots with 24/7 support and shuttle transport to Terminal 1.",
    area_landmark: "Kempegowda Airport Terminal 1",
    price_hourly: 100,
    price_daily: 600,
    price_monthly: -1, // N/A
    lat: 13.1986,
    lng: 77.7066,
    length: 18,
    breadth: 9,
    amenities: ['CCTV Camera', '24/7 Access', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Kempegowda+International+Airport/@13.1986,77.7066,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918066785555",
    is_sold: false,
    address_text: "KIAL Rd, Devanahalli, Bengaluru, Karnataka 560300"
  },
  {
    id: "pub_orion_mall",
    title: "Orion Mall Multilevel Parking (Gateway)",
    desc: "Premium multilevel car parking structure inside the Brigade Gateway enclave. Next to WTC Bangalore and Columbia Asia hospital.",
    area_landmark: "Orion Mall, Brigade Gateway",
    price_hourly: 40,
    price_daily: 300,
    price_monthly: 4000,
    lat: 12.9915,
    lng: 77.5550,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Orion+Mall/@12.9915,77.5550,17z",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918067282222",
    is_sold: false,
    address_text: "Dr Rajkumar Rd, Rajajinagar, Bengaluru, Karnataka 560055"
  },
  {
    id: "pub_cubbon_park",
    title: "Cubbon Park Public Parking (Near Press Club)",
    desc: "BBMP managed outdoor green parking lot. Open strictly during daytime park visiting hours. Scenic shaded parking slots.",
    area_landmark: "Press Club of Bengaluru, Cubbon Park",
    price_hourly: 10,
    price_daily: -1, // N/A
    price_monthly: -1, // N/A
    lat: 12.9774,
    lng: 77.5898,
    length: 14,
    breadth: 7,
    amenities: ['Gate Lock'],
    gmap_link: "https://www.google.com/maps/place/Cubbon+Park/@12.9774,77.5898,17z",
    image: "https://images.unsplash.com/photo-1596567189851-902eba51c964?auto=format&fit=crop&w=400&q=80",
    owner_phone: "N/A",
    is_sold: false,
    address_text: "Kasturba Rd, Behind Press Club, Bengaluru, Karnataka 560001"
  },
  {
    id: "pub_commercial_street",
    title: "BBMP Multi-Level Car Parking Complex",
    desc: "Newly constructed multi-level parking complex designed to ease vehicle congestion for shoppers visiting Commercial Street.",
    area_landmark: "Kamraj Rd / Commercial Street",
    price_hourly: -1, // N/A
    price_daily: -1,  // N/A
    price_monthly: -1, // N/A
    lat: 12.9818,
    lng: 77.6105,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Commercial+St,+Bengaluru,+Karnataka/@12.9818,77.6105,17z",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    owner_phone: "N/A",
    is_sold: false,
    address_text: "Tasker Town, Shivaji Nagar, Bengaluru, Karnataka 560001"
  },
  {
    id: "pub_falcon_city",
    title: "Forum Falcon City Parking Complex",
    desc: "Safe and clean indoor parking structure inside Forum Falcon City Mall. Equipped with security guards and automated parking tickets.",
    area_landmark: "Forum Falcon City Mall, Anjanapura",
    price_hourly: 30,
    price_daily: 200,
    price_monthly: -1, // N/A
    lat: 12.8931,
    lng: 77.5684,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Forum+Falcon+City+Mall/@12.8931,77.5684,17z",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918068940000",
    is_sold: false,
    address_text: "Kanakapura Rd, Konanakunte, Bengaluru, Karnataka 560062"
  },
  {
    id: "pub_yesvantpur_station",
    title: "Yesvantpur Junction Railway Station Parking",
    desc: "Large parking facility serving Yesvantpur Railway Station commuters. Separate areas for two-wheelers and four-wheelers.",
    area_landmark: "Yesvantpur Junction Entrance",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1, // N/A
    lat: 13.0235,
    lng: 77.5501,
    length: 16,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Yesvantpur+Junction/@13.0235,77.5501,17z",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=400&q=80",
    owner_phone: "N/A",
    is_sold: false,
    address_text: "Tumkur Rd, Yesvantpur, Bengaluru, Karnataka 560022"
  },
  {
    id: "pub_heathrow_t5",
    title: "London Heathrow Terminal 5 Car Park",
    desc: "Premium secure parking directly adjacent to Terminal 5. Features CCTV monitoring, security guard presence, and EV charging options.",
    area_landmark: "Heathrow Terminal 5, London",
    price_hourly: 8,
    price_daily: 45,
    price_monthly: -1,
    lat: 51.4700,
    lng: -0.4900,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Heathrow+Terminal+5/@51.4700,-0.4900,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+442087459000",
    is_sold: false,
    address_text: "Longford, Hounslow TW6 2GA, United Kingdom"
  },
  {
    id: "pub_westfield_london",
    title: "Westfield London Shopping Centre Parking",
    desc: "Underground parking spaces inside Westfield London (Shepherds Bush). Equipped with digital space tracking and active security guard patrol.",
    area_landmark: "Westfield London, Shepherds Bush",
    price_hourly: 3,
    price_daily: 18,
    price_monthly: -1,
    lat: 51.5065,
    lng: -0.2215,
    length: 14,
    breadth: 7,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Westfield+London/@51.5065,-0.2215,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+442033712300",
    is_sold: false,
    address_text: "Ariel Way, London W12 7GF, United Kingdom"
  },
  {
    id: "pub_jfk_t4",
    title: "JFK Airport Terminal 4 Blue Garage",
    desc: "Multi-level parking garage next to Terminal 4. Monitored 24/7 with dedicated customer assistance and quick terminal skywalk access.",
    area_landmark: "JFK Airport Terminal 4, New York",
    price_hourly: 12,
    price_daily: 70,
    price_monthly: -1,
    lat: 40.6430,
    lng: -73.7820,
    length: 16,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/JFK+Terminal+4/@40.6430,-73.7820,17z",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+17182444444",
    is_sold: false,
    address_text: "Queens, NY 11430, USA"
  },
  {
    id: "pub_times_square_garage",
    title: "Times Square Midtown Parking Garage",
    desc: "Professional valet-assisted indoor garage located in the heart of Midtown Manhattan. Secured gates and CCTV monitoring.",
    area_landmark: "Times Square Theatre District, NY",
    price_hourly: 25,
    price_daily: 85,
    price_monthly: -1,
    lat: 40.7580,
    lng: -73.9850,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'Gate Lock'],
    gmap_link: "https://www.google.com/maps/place/Times+Square/@40.7580,-73.9850,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+12122475050",
    is_sold: false,
    address_text: "220 W 42nd St, New York, NY 10036, USA"
  },
  {
    id: "pub_sydney_opera_carpark",
    title: "Sydney Opera House Wilson Car Park",
    desc: "Underground parking complex beneath the Sydney Opera House. High-end automated security and pedestrian links directly to Circular Quay.",
    area_landmark: "Sydney Opera House, Circular Quay",
    price_hourly: 15,
    price_daily: 60,
    price_monthly: -1,
    lat: -33.8568,
    lng: 151.2153,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Sydney+Opera+House/@-33.8568,151.2153,17z",
    image: "https://images.unsplash.com/photo-1596567189851-902eba51c964?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+61292507111",
    is_sold: false,
    address_text: "2 Macquarie St, Sydney NSW 2000, Australia"
  },
  {
    id: "pub_dubai_mall_parking",
    title: "Dubai Mall Grand Parking Complex",
    desc: "Huge multi-level indoor parking with smart space indicators and electric vehicle charging bays. Directly connected to Dubai Mall.",
    area_landmark: "Dubai Mall Entrance, Downtown Dubai",
    price_hourly: -1, // Free parking
    price_daily: -1,
    price_monthly: -1,
    lat: 25.1985,
    lng: 55.2796,
    length: 16,
    breadth: 8.5,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/The+Dubai+Mall/@25.1985,55.2796,17z",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+97143627500",
    is_sold: false,
    address_text: "Financial Center Rd, Downtown Dubai, United Arab Emirates"
  },
  {
    id: "pub_shibuya_crossing",
    title: "Shibuya Crossing District Car Park",
    desc: "Subterranean parking facility in Shibuya Tokyo. Highly secure automated mechanical stackers and 24/7 customer service.",
    area_landmark: "Shibuya Station, Tokyo",
    price_hourly: 600, // yen approx
    price_daily: 3000,
    price_monthly: -1,
    lat: 35.6595,
    lng: 139.7005,
    length: 14,
    breadth: 7,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Shibuya+Crossing/@35.6595,139.7005,17z",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+81334631211",
    is_sold: false,
    address_text: "1 Chome-2-1 Shibuya, Shibuya City, Tokyo 150-0002, Japan"
  },
  {
    id: "pub_mumbai_airport_t2",
    title: "CSMIA Terminal 2 Multilevel Car Park",
    desc: "Spacious multilevel car parking garage servicing Mumbai Terminal 2 passengers. Features premium slots, EV chargers, and quick terminal entry.",
    area_landmark: "Terminal 2 Departure Gates, Mumbai",
    price_hourly: 150,
    price_daily: 750,
    price_monthly: -1,
    lat: 19.0886,
    lng: 72.8680,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Chhatrapati+Shivaji+Maharaj+International+Airport+Mumbai/@19.0886,72.8680,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912266851010",
    is_sold: false,
    address_text: "Sahar Rd, Andheri East, Mumbai, Maharashtra 400099, India"
  },
  {
    id: "pub_mumbai_palladium",
    title: "Phoenix Palladium Mall Parking Structure",
    desc: "Dedicated shoppers and visitors indoor parking complex inside High Street Phoenix Palladium, Lower Parel. Highly guarded.",
    area_landmark: "Phoenix Palladium, Lower Parel, Mumbai",
    price_hourly: 50,
    price_daily: 400,
    price_monthly: -1,
    lat: 18.9943,
    lng: 72.8256,
    length: 14,
    breadth: 7.5,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Phoenix+Palladium/@18.9943,72.8256,17z",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912243339999",
    is_sold: false,
    address_text: "Senapati Bapat Marg, Lower Parel, Mumbai, Maharashtra 400013, India"
  },
  {
    id: "pub_delhi_cp_block_e",
    title: "NDMC CP E-Block Underground Car Park",
    desc: "Multi-level underground parking facility at Connaught Place. Very convenient for shoppers, merchants, and commuters visiting CP.",
    area_landmark: "Connaught Place Block-E, Delhi",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 28.6304,
    lng: 77.2201,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Connaught+Place,+New+Delhi,+Delhi+110001/@28.6304,77.2201,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+911123363600",
    is_sold: false,
    address_text: "Connaught Place, Block E, New Delhi, Delhi 110001, India"
  },
  {
    id: "pub_delhi_airport_t3",
    title: "IGIA Terminal 3 Multilevel Car Park",
    desc: "Official multi-level transit parking lot for Delhi Airport Terminal 3. Covered bays, luggage assistance, and 24/7 security guard presence.",
    area_landmark: "Indira Gandhi Airport Terminal 3, Delhi",
    price_hourly: 150,
    price_daily: 600,
    price_monthly: -1,
    lat: 28.5562,
    lng: 77.1000,
    length: 16,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Indira+Gandhi+International+Airport/@28.5562,77.1000,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+911244797300",
    is_sold: false,
    address_text: "Palam, New Delhi, Delhi 110037, India"
  },
  {
    id: "pub_paris_garedunord",
    title: "Gare du Nord Effia Car Park",
    desc: "Underground parking at Gare du Nord Train Station. 24/7 security guard, CCTV, electronic gating, and covered spaces.",
    area_landmark: "Gare du Nord Train Station, Paris",
    price_hourly: 5,
    price_daily: 36,
    price_monthly: -1,
    lat: 48.8809,
    lng: 2.3553,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'Gate Lock'],
    gmap_link: "https://www.google.com/maps/place/Gare+du+Nord/@48.8809,2.3553,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+33155825050",
    is_sold: false,
    address_text: "18 Rue de Dunkerque, 75010 Paris, France"
  },
  {
    id: "pub_singapore_changi_t3",
    title: "Changi Airport Terminal 3 Main Car Park",
    desc: "State of the art parking bays inside Changi Terminal 3. High security, electronic vacancy tracking, and direct terminal access.",
    area_landmark: "Changi Airport Terminal 3, Singapore",
    price_hourly: 3,
    price_daily: 35,
    price_monthly: -1,
    lat: 1.3537,
    lng: 103.9877,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Singapore+Changi+Airport/@1.3537,103.9877,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+6565956868",
    is_sold: false,
    address_text: "Airport Blvd, Singapore 819663"
  },
  {
    id: "pub_singapore_mbs",
    title: "Marina Bay Sands Integrated Car Park",
    desc: "Luxury undercover parking garage at MBS Hotel and Convention Centre. CCTV and automated parking ticket guidance system.",
    area_landmark: "Marina Bay Sands, Singapore",
    price_hourly: 8,
    price_daily: 48,
    price_monthly: -1,
    lat: 1.2829,
    lng: 103.8584,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Marina+Bay+Sands/@1.2829,103.8584,17z",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+6566888888",
    is_sold: false,
    address_text: "10 Bayfront Ave, Singapore 018956"
  },
  {
    id: "pub_toronto_pearson",
    title: "Pearson Airport Terminal 1 Garage",
    desc: "Extremely secure multi-level airport parking facility. Monitored with camera coverage, 24/7 help desk, and skyway access.",
    area_landmark: "Toronto Pearson Terminal 1, Mississauga",
    price_hourly: 10,
    price_daily: 50,
    price_monthly: -1,
    lat: 43.6777,
    lng: -79.6248,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Toronto+Pearson+International+Airport/@43.6777,-79.6248,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+14167763000",
    is_sold: false,
    address_text: "6301 Silver Dart Dr, Mississauga, ON L5P 1B2, Canada"
  },
  {
    id: "pub_chicago_millennium",
    title: "Millennium Park Underground Garage",
    desc: "Huge underground parking facility under Millennium Park Chicago. Safe, fully lit, and guarded 24/7.",
    area_landmark: "Millennium Park Loop, Chicago",
    price_hourly: 16,
    price_daily: 46,
    price_monthly: -1,
    lat: 41.8827,
    lng: -87.6227,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Millennium+Park/@41.8827,-87.6227,17z",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+13126160800",
    is_sold: false,
    address_text: "5 S Columbus Dr, Chicago, IL 60601, USA"
  },
  {
    id: "pub_sf_unionsquare",
    title: "Union Square Plaza Garage",
    desc: "Underground parking garage directly beneath Union Square Plaza. Active security, elevators, and charging stations.",
    area_landmark: "Union Square Shopping District, SF",
    price_hourly: 6,
    price_daily: 42,
    price_monthly: -1,
    lat: 37.7879,
    lng: -122.4074,
    length: 14,
    breadth: 7,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Union+Square/@37.7879,-122.4074,17z",
    image: "https://images.unsplash.com/photo-1596567189851-902eba51c964?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+14153970300",
    is_sold: false,
    address_text: "333 Post St, San Francisco, CA 94108, USA"
  },
  {
    id: "pub_capetown_waterfront",
    title: "V&A Waterfront Victoria Wharf Car Park",
    desc: "Multi-level covered shopping mall parking with CCTV coverage, biometric guard checkpoints, and automated ticketing.",
    area_landmark: "V&A Waterfront Retail Gates, Cape Town",
    price_hourly: 20,
    price_daily: 120,
    price_monthly: -1,
    lat: -33.9036,
    lng: 18.4231,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/V%26A+Waterfront/@-33.9036,18.4231,17z",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+27214087500",
    is_sold: false,
    address_text: "19 Dock Rd, V&A Waterfront, Cape Town 8001, South Africa"
  },
  {
    id: "pub_kolkata_airport",
    title: "NSCBIA Terminal 1 Parking Area",
    desc: "Open and covered car parking options outside Kolkata Netaji Subhash Chandra Bose Airport. Automated gates and helpline.",
    area_landmark: "Kolkata NSCBIA Airport Terminal",
    price_hourly: 100,
    price_daily: 500,
    price_monthly: -1,
    lat: 22.6547,
    lng: 88.4467,
    length: 16,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Netaji+Subhash+Chandra+Bose+International+Airport/@22.6547,88.4467,17z",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+913325111926",
    is_sold: false,
    address_text: "Jessore Rd, Dum Dum, Kolkata, West Bengal 700052, India"
  },
  {
    id: "pub_chennai_airport",
    title: "Chennai International Airport Multilevel Car Park",
    desc: "Covered multilevel car parking structure inside the airport complex. Fully guided with digital vacancy screens and passenger walkway.",
    area_landmark: "Chennai Airport T1/T2 Departure",
    price_hourly: 100,
    price_daily: 600,
    price_monthly: -1,
    lat: 12.9816,
    lng: 80.1707,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Chennai+International+Airport/@12.9816,80.1707,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914422560551",
    is_sold: false,
    address_text: "Great Southern Trunk Rd, Meenambakkam, Chennai, Tamil Nadu 600027, India"
  },
  {
    id: "pub_hyderabad_airport",
    title: "Rajiv Gandhi Airport T1 Car Parking Complex",
    desc: "Huge open and semi-covered multi-zone airport car park. Features premium valet zones, CCTV, and EV charging points.",
    area_landmark: "RGIA Terminal 1 Departure, Shamshabad",
    price_hourly: 100,
    price_daily: 600,
    price_monthly: -1,
    lat: 17.2403,
    lng: 78.4294,
    length: 16,
    breadth: 8.5,
    amenities: ['CCTV Camera', '24/7 Access', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Rajiv+Gandhi+International+Airport/@17.2403,78.4294,17z",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914066523900",
    is_sold: false,
    address_text: "Shamshabad, Hyderabad, Telangana 500409, India"
  },
  {
    id: "pub_bengaluru_forum",
    title: "Forum Mall Parking Lot (Koramangala)",
    desc: "Multi-level underground parking spaces inside the Nexus Forum Mall Koramangala. CCTV, automated ticketing, and EV charger access.",
    area_landmark: "Forum Nexus Mall, Koramangala",
    price_hourly: 40,
    price_daily: 250,
    price_monthly: -1,
    lat: 12.9344,
    lng: 77.6111,
    length: 14,
    breadth: 7.5,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Nexus+Forum+Mall/@12.9344,77.6111,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918022067803",
    is_sold: false,
    address_text: "Hosur Rd, Koramangala, Bengaluru, Karnataka 560095, India"
  },
  {
    id: "pub_mumbai_csmt",
    title: "CSMT Mumbai Railway Station Car Park",
    desc: "Official Indian Railways public car parking lot at Chhatrapati Shivaji Maharaj Terminus. Open 24/7 with manual ticketing and security.",
    area_landmark: "CSMT Main Entrance, Fort",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 18.9400,
    lng: 72.8354,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Chhatrapati+Shivaji+Maharaj+Terminus/@18.9400,72.8354,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912222621450",
    is_sold: false,
    address_text: "Chhatrapati Shivaji Maharaj Terminus, Fort, Mumbai, Maharashtra 400001, India"
  },
  {
    id: "pub_mumbai_central",
    title: "Mumbai Central Station Public Parking",
    desc: "Standard public parking space at Mumbai Central Railway Station. Multi-zone layout with dedicated 2-wheeler and 4-wheeler rows.",
    area_landmark: "Mumbai Central Station Gates",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 18.9696,
    lng: 72.8193,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Mumbai+Central/@18.9696,72.8193,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912223070197",
    is_sold: false,
    address_text: "Mumbai Central Railway Station, Marg, Mumbai, Maharashtra 400008, India"
  },
  {
    id: "pub_delhi_ndls",
    title: "New Delhi Railway Station (NDLS) Parking",
    desc: "Main entry gate transit parking at New Delhi Railway Station. Covered and open-air parking with round the clock security.",
    area_landmark: "NDLS Main Entrance (Paharganj side)",
    price_hourly: 30,
    price_daily: 200,
    price_monthly: -1,
    lat: 28.6418,
    lng: 77.2208,
    length: 16,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard', 'Covered Parking'],
    gmap_link: "https://www.google.com/maps/place/New+Delhi+Railway+Station/@28.6418,77.2208,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+911123340000",
    is_sold: false,
    address_text: "Bhavbhuti Marg, Ratan Lal Market, Kamla Market, New Delhi, Delhi 110006, India"
  },
  {
    id: "pub_delhi_nizamuddin",
    title: "Hazrat Nizamuddin Railway Station Parking",
    desc: "Indian Railways public parking zone at Hazrat Nizamuddin Station. Secure entry gates and manual token checking.",
    area_landmark: "Hazrat Nizamuddin Station Gates",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 28.5889,
    lng: 77.2536,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Hazrat+Nizamuddin+Railway+Station/@28.5889,77.2536,17z",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+911124359573",
    is_sold: false,
    address_text: "Hazrat Nizamuddin Railway Station, Nizamuddin East, New Delhi, Delhi 110013, India"
  },
  {
    id: "pub_chennai_central",
    title: "MGR Central Railway Station Parking",
    desc: "Spacious transit parking at Chennai Central station. Features modern automated token barriers and 24/7 security guard presence.",
    area_landmark: "MGR Central Main Gate",
    price_hourly: 25,
    price_daily: 180,
    price_monthly: -1,
    lat: 13.0827,
    lng: 80.2754,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Puratchi+Thalaivar+Dr.+M.G.+Ramachandran+Central+Railway+Station/@13.0827,80.2754,17z",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914425350303",
    is_sold: false,
    address_text: "Kannappar Thidal, Periyamet, Chennai, Tamil Nadu 600003, India"
  },
  {
    id: "pub_kolkata_howrah",
    title: "Howrah Junction Railway Station Parking",
    desc: "Large transit car park adjacent to the iconic Howrah Railway Station. CCTV coverage and manual ticket billing counters.",
    area_landmark: "Howrah Station Entrance",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 22.5833,
    lng: 88.3417,
    length: 16,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Howrah+Junction/@22.5833,88.3417,17z",
    image: "https://images.unsplash.com/photo-1596567189851-902eba51c964?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+913326601748",
    is_sold: false,
    address_text: "Howrah Station, Howrah, West Bengal 711101, India"
  },
  {
    id: "pub_hyderabad_secunderabad",
    title: "Secunderabad Junction Public Parking",
    desc: "Secure transit parking slots near Secunderabad Station platform entries. Managed by South Central Railway authorized agents.",
    area_landmark: "Secunderabad Station Main Entrance",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 17.4339,
    lng: 78.5017,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Secunderabad+Junction+Railway+Station/@17.4339,78.5017,17z",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914027782613",
    is_sold: false,
    address_text: "Secunderabad Railway Station, Secunderabad, Hyderabad, Telangana 500003, India"
  },
  {
    id: "pub_pune_junction",
    title: "Pune Junction Station General Parking",
    desc: "Public car and bike parking layout located outside Pune Junction. Shaded sections, manual ticket tokens, and active guard patrol.",
    area_landmark: "Pune Junction Main Gate",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 18.5289,
    lng: 73.8744,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Pune+Junction+Railway+Station/@18.5289,73.8744,17z",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912026122650",
    is_sold: false,
    address_text: "Pune Junction Railway Station, Agarkar Nagar, Pune, Maharashtra 411001, India"
  },
  {
    id: "pub_ahmedabad_kalupur",
    title: "Ahmedabad Junction (Kalupur) Public Car Park",
    desc: "Multi-zone public parking at Kalupur entrance of Ahmedabad Junction station. Fully fenced and managed for traveler safety.",
    area_landmark: "Kalupur Station Entrance",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 23.0269,
    lng: 72.6009,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Ahmedabad+Junction/@23.0269,72.6009,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+917922112108",
    is_sold: false,
    address_text: "Ahmedabad Junction Railway Station, Kalupur, Ahmedabad, Gujarat 380002, India"
  },
  {
    id: "pub_jaipur_junction",
    title: "Jaipur Junction Station Car Parking",
    desc: "Official passenger parking facility at Jaipur Junction. Regular security patrols, spacious lanes, and flat day rates available.",
    area_landmark: "Jaipur Junction Main Gate",
    price_hourly: 20,
    price_daily: 150,
    price_monthly: -1,
    lat: 26.9197,
    lng: 75.7877,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Jaipur+Junction/@26.9197,75.7877,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+911412204550",
    is_sold: false,
    address_text: "Jaipur Junction Railway Station, Gopalbari, Jaipur, Rajasthan 302006, India"
  },
  {
    id: "pub_kochi_ernakulam",
    title: "Ernakulam Junction (South) Public Parking",
    desc: "Reliable station-side transit parking lot. Convenient for daily rail commuters with separate zones for long-term and short-term parking.",
    area_landmark: "Ernakulam South Station Entrance",
    price_hourly: 15,
    price_daily: 120,
    price_monthly: -1,
    lat: 9.9678,
    lng: 76.2889,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Ernakulam+Junction+(South)/@9.9678,76.2889,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914842375131",
    is_sold: false,
    address_text: "Ernakulam Junction Railway Station, Kochi, Kerala 682016, India"
  },
  {
    id: "pub_lulu_kochi",
    title: "Lulu International Mall Multilevel Parking",
    desc: "Asia's largest mall multilevel parking garage. State-of-the-art automated space tracking, EV charging, 24/7 security, and guide staff.",
    area_landmark: "Lulu Mall Kochi, Edappally",
    price_hourly: 30,
    price_daily: 250,
    price_monthly: -1,
    lat: 10.0278,
    lng: 76.3080,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging', '24/7 Access'],
    gmap_link: "https://www.google.com/maps/place/Lulu+International+Shopping+Mall/@10.0278,76.3080,17z",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914842721111",
    is_sold: false,
    address_text: "34/1000, NH 66, Edappally, Kochi, Kerala 682024, India"
  },
  {
    id: "pub_phoenix_pune",
    title: "Phoenix Marketcity Mall Parking (Viman Nagar)",
    desc: "Elite multilevel underground parking structure at Phoenix Marketcity Pune. Modern security, RFID scanning, and EV vehicle slots.",
    area_landmark: "Phoenix Marketcity Viman Nagar",
    price_hourly: 40,
    price_daily: 300,
    price_monthly: -1,
    lat: 18.5622,
    lng: 73.9167,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Phoenix+Marketcity+Pune/@18.5622,73.9167,17z",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912066890000",
    is_sold: false,
    address_text: "Viman Nagar Rd, Clover Park, Viman Nagar, Pune, Maharashtra 411014, India"
  },
  {
    id: "pub_infiniti_andheri",
    title: "Infiniti Mall Car Park (Andheri West)",
    desc: "Covered multi-level shoppers parking facility at Infiniti Mall Andheri West. Smart security checkpoint and guide assistance.",
    area_landmark: "Infiniti Mall Andheri West",
    price_hourly: 30,
    price_daily: 250,
    price_monthly: -1,
    lat: 19.1411,
    lng: 72.8311,
    length: 14,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Infiniti+Mall/@19.1411,72.8311,17z",
    image: "https://images.unsplash.com/photo-1596567189851-902eba51c964?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912261801011",
    is_sold: false,
    address_text: "New Link Rd, Phase D, Oshiwara, Andheri West, Mumbai, Maharashtra 400053, India"
  },
  {
    id: "pub_inorbit_malad",
    title: "Inorbit Mall Multilevel Parking (Malad West)",
    desc: "Premium subterranean car park with automated toll booths, high-def CCTV surveillance, and 24/7 security guard patrol.",
    area_landmark: "Inorbit Mall Malad West",
    price_hourly: 30,
    price_daily: 250,
    price_monthly: -1,
    lat: 19.1764,
    lng: 72.8364,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Inorbit+Mall/@19.1764,72.8364,17z",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912266490400",
    is_sold: false,
    address_text: "Link Rd, Malad, Mumbai Suburban, Mumbai, Maharashtra 400064, India"
  },
  {
    id: "pub_phoenix_kurla",
    title: "Phoenix Marketcity Car Park (Kurla)",
    desc: "Vast multi-level basement car parking structure inside Phoenix Marketcity Kurla. Advanced parking space detection system.",
    area_landmark: "Phoenix Marketcity Kurla Entrance",
    price_hourly: 40,
    price_daily: 300,
    price_monthly: -1,
    lat: 19.0864,
    lng: 72.8890,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Phoenix+Marketcity/@19.0864,72.8890,17z",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+912261801100",
    is_sold: false,
    address_text: "Lal Bahadur Shastri Marg, Kurla West, Mumbai, Maharashtra 400070, India"
  },
  {
    id: "pub_select_citywalk",
    title: "Select Citywalk Mall Underground Car Park",
    desc: "Highly secured underground multi-level parking complex at Select Citywalk Mall. Automated parking token kiosks, EV charging, and 24/7 guards.",
    area_landmark: "Select Citywalk Saket",
    price_hourly: 40,
    price_daily: 300,
    price_monthly: -1,
    lat: 28.5286,
    lng: 77.2194,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Select+CITYWALK/@28.5286,77.2194,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+911142666666",
    is_sold: false,
    address_text: "A-3, District Centre, Sector 6, Pushp Vihar, New Delhi, Delhi 110017, India"
  },
  {
    id: "pub_dlf_promenade",
    title: "DLF Promenade Mall Parking Lot",
    desc: "Multi-zone open and covered premium car parking. Features security checking, EV chargers, and direct elevator access into the mall.",
    area_landmark: "DLF Promenade Vasant Kunj",
    price_hourly: 40,
    price_daily: 300,
    price_monthly: -1,
    lat: 28.5428,
    lng: 77.1558,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/DLF+Promenade/@28.5428,77.1558,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+911146066600",
    is_sold: false,
    address_text: "Nelson Mandela Marg, Vasant Kunj II, Vasant Kunj, New Delhi, Delhi 110070, India"
  },
  {
    id: "pub_phoenix_velachery",
    title: "Phoenix Marketcity Parking (Velachery)",
    desc: "Elite shopping destination multi-level parking lot with automated entry sensors, security patrols, and covered spaces.",
    area_landmark: "Phoenix Marketcity Velachery",
    price_hourly: 30,
    price_daily: 250,
    price_monthly: -1,
    lat: 12.9917,
    lng: 80.2172,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Phoenix+Marketcity/@12.9917,80.2172,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914430083008",
    is_sold: false,
    address_text: "142, Velachery Rd, Indira Gandhi Nagar, Velachery, Chennai, Tamil Nadu 600042, India"
  },
  {
    id: "pub_manisquare_kolkata",
    title: "Mani Square Mall Multi-Level Parking",
    desc: "Safe and convenient multi-level indoor car park at Mani Square Mall on EM Bypass. CCTV, automated billing, and guide assistants.",
    area_landmark: "Mani Square EM Bypass",
    price_hourly: 30,
    price_daily: 250,
    price_monthly: -1,
    lat: 22.5786,
    lng: 88.4019,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Mani+Square/@22.5786,88.4019,17z",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+913323588100",
    is_sold: false,
    address_text: "164/1, Maniktala Main Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054, India"
  },
  {
    id: "pub_quest_kolkata",
    title: "Quest Mall Luxury Valet & Self-Parking",
    desc: "Premium underground self-parking and valet-assisted parking slots inside Quest Mall. High-security checking and EV chargers available.",
    area_landmark: "Quest Mall Ballygunge",
    price_hourly: 40,
    price_daily: 300,
    price_monthly: -1,
    lat: 22.5392,
    lng: 88.3619,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Quest+Mall/@22.5392,88.3619,17z",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+913330689999",
    is_sold: false,
    address_text: "33, Syed Amir Ali Ave, Park Circus, Ballygunge, Kolkata, West Bengal 700017, India"
  },
  {
    id: "pub_inorbit_hyderabad",
    title: "Inorbit Mall Parking Complex (Madhapur)",
    desc: "Underground shoppers parking with 24/7 security patrol, CCTV cameras, automated tickets, and direct escalator connections to Cyberabad IT zone.",
    area_landmark: "Inorbit Mall Mindspace Madhapur",
    price_hourly: 30,
    price_daily: 250,
    price_monthly: -1,
    lat: 17.4348,
    lng: 78.3831,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Inorbit+Mall+Cyberabad/@17.4348,78.3831,17z",
    image: "https://images.unsplash.com/photo-1596567189851-902eba51c964?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914044888888",
    is_sold: false,
    address_text: "Sapiens Path, Mindspace, Madhapur, Hyderabad, Telangana 500081, India"
  },
  {
    id: "pub_majestic_busstand",
    title: "Kempegowda Majestic Bus Stand Car Park",
    desc: "BMTC managed public parking at Majestic Bus Stand. Ideal for local commuters matching transit schedules. Open 24/7.",
    area_landmark: "Majestic Bus Stand Main Terminal",
    price_hourly: 15,
    price_daily: 120,
    price_monthly: -1,
    lat: 12.9778,
    lng: 77.5728,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Kempegowda+Bus+Station/@12.9778,77.5728,17z",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+918022975615",
    is_sold: false,
    address_text: "Kempegowda Bus Station, Majestic, Bengaluru, Karnataka 560009, India"
  },
  {
    id: "pub_koyambedu_cmbt",
    title: "Koyambedu CMBT Bus Stand Public Parking",
    desc: "CMDA managed transit parking slots near the main gates of Koyambedu Bus Terminus. Heavy vehicle security and manual barrier ticketing.",
    area_landmark: "Koyambedu CMBT Main Gate",
    price_hourly: 15,
    price_daily: 120,
    price_monthly: -1,
    lat: 13.0678,
    lng: 80.2056,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Chennai+Mofussil+Bus+Terminus/@13.0678,80.2056,17z",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914424791300",
    is_sold: false,
    address_text: "Koyambedu CMBT, Koyambedu, Chennai, Tamil Nadu 600107, India"
  },
  {
    id: "pub_hyderabad_mgbs",
    title: "MGBS Hyderabad Bus Station Public Parking",
    desc: "TSRTC public passenger parking facility at MGBS. Dedicated lanes, fenced perimeter, and regular security checkouts.",
    area_landmark: "MGBS Main Platform Entrance",
    price_hourly: 15,
    price_daily: 120,
    price_monthly: -1,
    lat: 17.3779,
    lng: 78.4862,
    length: 15,
    breadth: 8,
    amenities: ['24/7 Access', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Mahatma+Gandhi+Bus+Station/@17.3779,78.4862,17z",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+914024618063",
    is_sold: false,
    address_text: "Mahatma Gandhi Bus Station, Gowliguda, Hyderabad, Telangana 500095, India"
  },
  {
    id: "pub_paris_cdg",
    title: "Charles de Gaulle Airport (CDG) Terminal 2 Parking",
    desc: "Premium covered airport parking at Paris CDG. Video surveillance, pedestrian walkway to Terminal 2, and charging stations.",
    area_landmark: "CDG Terminal 2 Departure",
    price_hourly: 6,
    price_daily: 39,
    price_monthly: -1,
    lat: 49.0097,
    lng: 2.5479,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Paris+Charles+de+Gaulle+Airport/@49.0097,2.5479,17z",
    image: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+33170363950",
    is_sold: false,
    address_text: "95700 Roissy-en-France, France"
  },
  {
    id: "pub_lax_economy",
    title: "LAX Economy Parking Structure",
    desc: "Official economy parking facility at LAX. High-tech space counting, free EV charging, shuttle service to all terminals, and 24/7 surveillance.",
    area_landmark: "LAX Economy Lot Area",
    price_hourly: 8,
    price_daily: 35,
    price_monthly: -1,
    lat: 33.9416,
    lng: -118.4085,
    length: 16,
    breadth: 8.5,
    amenities: ['CCTV Camera', '24/7 Access', 'Security Guard', 'EV Charging'],
    gmap_link: "https://www.google.com/maps/place/Los+Angeles+International+Airport/@33.9416,-118.4085,17z",
    image: "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+13106465252",
    is_sold: false,
    address_text: "1 World Way, Los Angeles, CA 90045, USA"
  },
  {
    id: "pub_amsterdam_schiphol",
    title: "Schiphol Airport P1 Short & Long Parking",
    desc: "Sheltered modern parking structure a short walk from departure terminals. License plate recognition and camera-monitored zones.",
    area_landmark: "AMS Schiphol Terminal Entrance",
    price_hourly: 4,
    price_daily: 42,
    price_monthly: -1,
    lat: 52.3105,
    lng: 4.7683,
    length: 15,
    breadth: 8,
    amenities: ['CCTV Camera', '24/7 Access', 'Covered Parking', 'Security Guard'],
    gmap_link: "https://www.google.com/maps/place/Amsterdam+Airport+Schiphol/@52.3105,4.7683,17z",
    image: "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=400&q=80",
    owner_phone: "+31206019111",
    is_sold: false,
    address_text: "Evert van de Beekstraat 202, 1118 CP Schiphol, Netherlands"
  }
];

async function seed() {
  console.log("=== SEEDING PUBLIC PARKING SPOTS ===");
  // 1. Initialize DB to ensure connection and schemas
  await db.initDb();

  // 2. Fetch existing listings to prevent primary key collisions
  const existingListings = await db.dbGetListings() || [];
  const existingIds = new Set(existingListings.map(l => l.id));

  // 3. Seed Owners
  for (const owner of PUBLIC_OWNERS) {
    const existingOwner = await db.dbGetOwner(owner.phone);
    if (!existingOwner) {
      console.log(`[SEED] Adding Owner: ${owner.name} (${owner.phone})`);
      await db.dbSaveOwner(owner);
    } else {
      console.log(`[SEED] Owner already exists: ${owner.name} (${owner.phone})`);
    }
  }

  // 4. Seed Listings
  for (const listing of PUBLIC_LISTINGS) {
    if (!existingIds.has(listing.id)) {
      console.log(`[SEED] Seeding Listing: ${listing.title}`);
      
      // Structure standard data payload matching backend format
      const dataPayload = {
        id: listing.id,
        title: listing.title,
        desc: listing.desc,
        area_landmark: listing.area_landmark,
        price_hourly: listing.price_hourly,
        price_daily: listing.price_daily,
        price_monthly: listing.price_monthly,
        lat: listing.lat,
        lng: listing.lng,
        length: listing.length,
        breadth: listing.breadth,
        amenities: listing.amenities,
        gmap_link: listing.gmap_link,
        gmap_link_regen: listing.gmap_link,
        image: listing.image,
        owner_phone: listing.owner_phone,
        is_sold: listing.is_sold,
        created_at: Date.now() / 1000,
        address_text: listing.address_text
      };

      await db.dbAddListing(dataPayload);
    } else {
      console.log(`[SEED] Listing already exists: ${listing.title}`);
    }
  }

  console.log("[SUCCESS] Seeding complete! Database is populated with public spots.");
}

// Check if running directly to execute
if (require.main === module) {
  seed()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error("[ERROR] Seeding failed:", err.message);
      process.exit(1);
    });
}

module.exports = { seed };
